# MirrorMaker 2 — replicate cluster A orders topic to cluster B
clusters = A, B
A.bootstrap.servers = localhost:9092
B.bootstrap.servers = localhost:9096

A->B.enabled = true
A->B.topics = orders

replication.factor = 1
checkpoints.topic.replication.factor = 1
heartbeats.topic.replication.factor = 1
offset-syncs.topic.replication.factor = 1
offset.storage.replication.factor = 1
status.storage.replication.factor = 1
config.storage.replication.factor = 1
